image: $CI_REGISTRY_IMAGE
stages:
  - docker-stage
  - build
#  - yarn-stage
#  - test

docker-job:
  image: registry.gitlab.com/replatf0rm/docker-compose-ci:latest
  stage: docker-stage
  tags:
    - amd64
  services:
    - name: docker:19.03.12-dind
      alias: docker
  variables:
    GIT_DEPTH: 1
    DOCKER_TLS_CERTDIR: "/certs"
    CI: "true"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker-compose build
    - docker-compose push
    - docker cp $(docker create --rm "$CI_REGISTRY_IMAGE"):/app/out public
  artifacts:
    paths:
      - public/
  only:
    refs:
      - master

pages:
  stage: build
  tags:
    - amd64
  script:
    - mv public/ static/; mv out/ public/
  variables:
    GIT_DEPTH: 1
    DOCKER_TLS_CERTDIR: "/certs"
    CI: "true"
  cache:
    key: $CI_PROJECT_NAME
    policy: pull-push
    paths:
      - public/
  artifacts:
    paths:
      - public/
  only:
    refs:
      - master

